---
title: Kopieer delen tussen sprite-uiterlijken
hero_image: images/banner.png
description: Kopieer delen tussen sprite-uiterlijken
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Kopieer delen tussen sprite-uiterlijken
