---
title: Copy parts between sprite costumes
hero_image: images/banner.png
description: Copy parts between sprite costumes
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Copy parts between sprite costumes
