---
title: Copïo rannau rhwng gwisgoedd corluniau
hero_image: images/banner.png
description: Copïo rannau rhwng gwisgoedd corluniau
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Copïo rannau rhwng gwisgoedd corluniau
