---
title: Copie partes entre fantasias do ator
hero_image: images/banner.png
description: Copie partes entre fantasias de sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Copie partes entre fantasias do ator
