---
title: Copier des parties entre les costumes de sprite
hero_image: images/banner.png
description: Copier des parties entre les costumes de sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Copier des parties entre les costumes de sprite
