---
title: Copia elementi tra i diversi costumi di uno sprite
hero_image: images/banner.png
description: Copia elementi tra i diversi costumi di uno sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Copia elementi tra i diversi costumi di uno sprite
